# Generated by Django 5.0.6 on 2024-06-24 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('admin_email', models.EmailField(max_length=254, unique=True)),
                ('admin_password', models.CharField(max_length=255)),
                ('admin_cnic', models.CharField(max_length=15)),
                ('admin_phone_number', models.CharField(max_length=15)),
                ('admin_address', models.CharField(max_length=255)),
                ('admin_created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('P', 'Pending')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSection',
            fields=[
                ('class_section_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_section_name', models.CharField(max_length=100)),
                ('class_section_strength', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=100)),
                ('total_enrolled_students', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_paid', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('student_email', models.EmailField(max_length=254, unique=True)),
                ('student_father_name', models.CharField(max_length=100)),
                ('student_address', models.CharField(max_length=255)),
                ('student_phone_number', models.CharField(max_length=15)),
                ('student_guardian_phone_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('status', models.CharField(choices=[('E', 'Enabled'), ('D', 'Disabled')], max_length=1)),
                ('class_section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.classsection')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.studentclass')),
            ],
        ),
        migrations.AddField(
            model_name='classsection',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.studentclass'),
        ),
    ]
