# Generated by Django 5.0.6 on 2024-07-01 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('ClassID', models.AutoField(primary_key=True, serialize=False)),
                ('ClassName', models.CharField(max_length=100)),
                ('TotalEnrolledStudents', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('AdminID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('AdminEmail', models.EmailField(max_length=254, unique=True)),
                ('AdminCNIC', models.CharField(max_length=15, unique=True)),
                ('AdminPhoneNumber', models.CharField(max_length=15)),
                ('AdminAddress', models.TextField()),
                ('AdminStatus', models.CharField(max_length=50)),
                ('AdminCreatedAt', models.DateTimeField(auto_now_add=True)),
                ('Password', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSection',
            fields=[
                ('ClassSectionID', models.AutoField(primary_key=True, serialize=False)),
                ('ClassSectionName', models.CharField(max_length=100)),
                ('ClassSectionStrength', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_app.class')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('DateOfBirth', models.DateField()),
                ('Gender', models.CharField(max_length=10)),
                ('FeeAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('FeePaid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('StudentEmail', models.EmailField(max_length=254, unique=True)),
                ('StudentPhoneNumber', models.CharField(max_length=15)),
                ('StudentFatherName', models.CharField(max_length=100)),
                ('StudentGuardianPhoneNumber', models.CharField(max_length=15)),
                ('Status', models.CharField(max_length=50)),
                ('StudentAddress', models.TextField()),
                ('Password', models.CharField(max_length=100)),
                ('ClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_app.class')),
                ('ClassSectionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_app.classsection')),
            ],
        ),
    ]
